### ISSUE TITLE
there maybe a mistake in client.py during updating local control variate

### ISSUE THREAD

**Issue by MrYYYYYYYYYYY** [ki-ljl/Scaffold-Federated-Learning#1]
The  local control variate update as follow in the origin papper.
<img width="473" alt="截屏2022-05-03 下午5 01 57" src="https://user-images.githubusercontent.com/41470007/166428272-d1d9d725-d0a8-4e38-ba71-9737f67019f2.png">

 When using Option 2, K means the number of local update steps which equals to E*L/B, E is local epoch, L is the size of local dataset, B is local batch size 
<img width="563" alt="截屏2022-05-03 下午4 58 22" src="https://user-images.githubusercontent.com/41470007/166427891-fb1dd833-c8ed-4879-99ee-2c55901ddb2f.png">
So I wonder if there is a mistake in client.py during updating local control variate at line 50
<img width="820" alt="image" src="https://user-images.githubusercontent.com/41470007/166429611-16c72d7d-1c56-4afe-91a9-0e71296e401a.png">

**Comment by ki-ljl** [comment]
You are right, the relevant error has been corrected, thanks for your question!
<img width="515" alt="image" src="https://user-images.githubusercontent.com/56509367/166456028-5a6f0fbf-1d5d-4735-ac1f-86da4588354a.png">

**Comment by MrYYYYYYYYYYY** [comment]
Thanks for your reply! I think this issue can be closed now :)  .
